### ISSUE TITLE
[BUG] config file migration fails with macOS app bundle

### ISSUE THREAD

**Issue by T0mu** [SamSchott/maestral-dropbox#103]
**Describe the bug**
after 0.6.2 version maestral.app (OSX) it's not working anymore...
daemon start error, upgrading to 0.6.3 gives the same error
regression to 0.6.1 works.

launching from command line gives me the following output:
_Exception in thread maestral-daemon-maestral:
Traceback (most recent call last):
  File "configparser.py", line 788, in get
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 916, in __getitem__
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/collections/__init__.py", line 908, in __missing__
KeyError: 'excluded_folders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "maestral/daemon.py", line 194, in run_maestral_daemon
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "maestral/main.py", line 80, in <module>
  File "maestral/utils/housekeeping.py", line 121, in run_housekeeping
  File "maestral/utils/housekeeping.py", line 94, in migrate_user_config
  File "configparser.py", line 791, in get
configparser.NoOptionError: No option 'excluded_folders' in section: 'main'_
<img width="476" alt="Error Screenshot crop 2020-03-27 - 15 49 27" src="https://user-images.githubusercontent.com/14136369/77770422-8682e100-7045-11ea-911f-f8f2de26ce05.png">

**To Reproduce**
Just launch the app

**Expected behaviour**
Starting daemon
**System (please complete the following information):**
 - Maestral version: 0.6.2 0.6.3
 - OS: [e.g. Ubuntu] OSX 10.15.4 Catalina
 - Desktop environment: [e.g. Gnome 3.32] OSX
 - Qt version:

**Additional context**
that's all!

**Comment by SamSchott** [comment]
Thanks for the report. This seems to be an issue with migrating the configuration file after the update which only occurs with the macOS app bundle.

Could you post the contents of your configuration file here? It should be located at:

```
~/Library/Application Support/maestral/maestral.ini
```

Feel free to redact any personal information such as the Dropbox ID before posting.

**Comment by T0mu** [comment]
Hi Sam,
Enclosed you’ll find my Maestral.ini

Thank you for your swift reply….

All the best

Tomaso

____________________________
Cura ut valeas atque incluis redi
____________________________





Il giorno 27 mar 2020, alle ore 17:07, SamSchott <notifications@github.com<mailto:notifications@github.com>> ha scritto:



Thanks for the report. This seems to be an issue with migrating the configuration file after the update which only occurs with the macOS app bundle.

Could you post the contents of your configuration file here? It should be located at:

~/Library/Application Support/maestral/maestral.ini


Feel free to redact any personal information such as the Dropbox ID before posting.

**Comment by SamSchott** [comment]
I don't think email attachments work with github...

**Comment by T0mu** [comment]
corrected, sorry!

[maestral.ini.txt](https://github.com/SamSchott/maestral-dropbox/files/4395237/maestral.ini.txt)

**Comment by SamSchott** [comment]
Yes, this looks like a failed update of the config file. I suspect this is because the macOS bundle uses a different startup routine than the python package and it seems like the migration occurred too late.

For now, you can manually edit the config file to get things working again:

1. Remove the lines with `excluded_folders` and `excluded_files`.
2. If you you previously had any excluded folders, you can copy them over to `excluded_items`. The old list should should be in one of the backup files inside the "backup" folder at the same location.
3. Change `version = 11.0.0` to `version = 12.0.0`.

After that, starting Maestral should work again. I will look into fixing the update process...

**Comment by T0mu** [comment]
Your solution fixed it!
Thank you.
