### ISSUE TITLE
[BUG] Non 'latin-1' Filename / Paths fail in 'get_local_hash'

### ISSUE THREAD

**Issue by techman83** [SamSchott/maestral-dropbox#124]
**Describe the bug**
When synchronising files with extended characters, sync fails when running `get_local_hash`
```
2020-04-17 10:19:02 maestral.sync DEBUG: Equal revs for "/japanese/3a corporation/みんなの日本語初級i 本冊 第2版": local item is the same or newer than on Dropbox
2020-04-17 10:19:03 maestral.sync ERROR: Unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2664, in startup_worker
    sync.get_remote_folder()
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 343, in wrapper
    res = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 1892, in get_remote_folder
    _, s = self.apply_remote_changes(root_result, save_cursor=False)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2048, in apply_remote_changes
    res = self.create_local_entry(folder)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 343, in wrapper
    res = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2344, in create_local_entry
    conflict_check = self.check_download_conflict(entry)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2120, in check_download_conflict
    local_hash = get_local_hash(local_path)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 3035, in get_local_hash
    with open(local_path, 'rb') as f:
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 46-54: ordinal not in range(256)
```

**To Reproduce**
Attempt to sync directory or file with encoded charecters

**Expected behaviour**
Sync the files or skip them with a warning.

**System (please complete the following information):**
 - Maestral version: 0.6.4
 - OS: Ubuntu 18.04 Server
 - Desktop environment: None
 - Qt version: None

**Additional context**
Chucking `.encode()` on the `local_path` within the `get_local_hash` function meant it was able to read the filename, but I've only had a very cursory glance at the code and don't know the full consequences of doing that just yet :slightly_smiling_face: 

Definitely needs more than a cursory glance it would appear!
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 92-100: ordinal not in range(256)
Call stack:
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2664, in startup_worker
    sync.get_remote_folder()
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 343, in wrapper
    res = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 1892, in get_remote_folder
    _, s = self.apply_remote_changes(root_result, save_cursor=False)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2048, in apply_remote_changes
    res = self.create_local_entry(folder)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 343, in wrapper
    res = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2344, in create_local_entry
    conflict_check = self.check_download_conflict(entry)
  File "/usr/local/lib/python3.6/dist-packages/maestral/sync.py", line 2123, in check_download_conflict
    logger.debug('Equal content hashes for "%s": no conflict', dbx_path)
Message: 'Equal content hashes for "%s": no conflict'
Arguments: ('/japanese/3a corporation/\u307f\u3093\u306a\u306e\u65e5\u672c\u8a9e\u521d\u7d1ai \u672c\u518a \u7b2c2\u7248',)
```

If I get a chance I'll have a closer look and see if I can come up with a reasonable patch.

**Comment by SamSchott** [comment]
Strange, this should not be a problem. Is "/japanese/3a corporation/みんなの日本語初級i 本冊 第2版" the offending file? Because it seems like the conflicting check goes through for this one:

```
2020-04-17 10:19:02 maestral.sync DEBUG: Equal revs for "/japanese/3a corporation/みんなの日本語初級i 本冊 第2版": local item is the same or newer than on Dropbox
```

I suspect it may be the next file that fails. But this is unusual: the file is opened in binary mode so there should not be any encoding issues with its content. And why would Python try to encode the filename in latin-1?

**Comment by techman83** [comment]
Yes, it'll be the next file (actually it's a directory with characters that don't print). I'm thinking it's from the API as I can iterate over the files with a glob in python on my main machine.

I'll narrow down my testing and see if I can get a nicer example together and maybe a fix.

**Comment by techman83** [comment]
I got suspicious, as it worked on my dev machine and not where it was running.

Host where I want to run it
```
~/git/maestral-dropbox$ locale
LANG=en_AU
LANGUAGE=en_US:
LC_CTYPE="en_AU"
LC_NUMERIC="en_AU"
LC_TIME="en_AU"
LC_COLLATE="en_AU"
LC_MONETARY="en_AU"
LC_MESSAGES="en_AU"
LC_PAPER="en_AU"
LC_NAME="en_AU"
LC_ADDRESS="en_AU"
LC_TELEPHONE="en_AU"
LC_MEASUREMENT="en_AU"
LC_IDENTIFICATION="en_AU"
LC_ALL=
```
My machine:
```
 ~ locale
LANG=en_AU.UTF-8
LANGUAGE=en_AU:en
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER="en_AU.UTF-8"
LC_NAME="en_AU.UTF-8"
LC_ADDRESS="en_AU.UTF-8"
LC_TELEPHONE="en_AU.UTF-8"
LC_MEASUREMENT="en_AU.UTF-8"
LC_IDENTIFICATION="en_AU.UTF-8"
LC_ALL=
```
I'm sure buried somewhere that could be enforced, but ensuring switching the `CHARMAP` in `/etc/default/console-setup` to `UTF-8` sorted things out!

```bash
~/git/maestral-dropbox$ cat /etc/default/console-setup 
# CONFIGURATION FILE FOR SETUPCON

# Consult the console-setup(5) manual page.

ACTIVE_CONSOLES="/dev/tty[1-6]"

CHARMAP="UTF-8"

CODESET="Lat15"
FONTFACE="VGA"
FONTSIZE="8x16"

VIDEOMODE=

# The following is an example how to use a braille font
# FONT='lat9w-08.psf.gz brl-8x8.psf'
~/git/maestral-dropbox$ sudo systemctl daemon-reload && sudo systemctl restart console-setup.service
```


Calling `encode()` on `md.path_display` did get it to do the right things, but it's likely something well upstream of maestral. Anyway, all working now :slightly_smiling_face:

**Comment by SamSchott** [comment]
Glad its working now and yes, this seems well upstream.
