### ISSUE TITLE
Maestral spontaneously stopped working

### ISSUE THREAD

**Issue by someone1233** [SamSchott/maestral-dropbox#128]
Hello again! Maestral has been running good but a few days ago stopped working -- it stopped appearing in the tray at startup and running both "maestral" and "maestral gui" in the terminal gives an error:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/maestral", line 11, in <module>
    load_entry_point('maestral==0.6.4', 'console_scripts', 'maestral')()
  File "/home/user/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/home/user/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/home/user/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/.local/lib/python3.6/site-packages/maestral/cli.py", line 28, in <module>
    run_housekeeping()
  File "/home/user/.local/lib/python3.6/site-packages/maestral/utils/housekeeping.py", line 134, in run_housekeeping
    migrate_user_config(config_name)
  File "/home/user/.local/lib/python3.6/site-packages/maestral/utils/housekeeping.py", line 41, in migrate_user_config
    old_version = old_conf.get(UserConfig.DEFAULT_SECTION_NAME, 'version')
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'main'
```

I tried a few reboots & also updated to the latest version using the commands on the main page but it didn't make a difference. Also not sure if it's related but the last time Maestral was working I right clicked the tray icon & closed it from there, it's the only time I've ever done that & maestral hasn't worked since then. I can't think of anything else that's changed on the system. It's Linux Mint 19.3 Cinnamon. Thank you for any help!!

**Comment by SamSchott** [comment]
> Also not sure if it's related but the last time Maestral was working I right clicked the tray icon & closed it from there, it's the only time I've ever done that & maestral hasn't worked since then.

That shouldn't be a problem, the sync daemon will be shut down in exactly the same way.

I think the error is caused by an update of the config files going wrong at some point. The easiest way to fix this is to delete the config files and relink your Dropbox account. You can then select the existing Dropbox folder and choose to "merge" it to avoid downloading everything again. The files are located at `~/.config/maestral` and deleting the whole folder should do the job.

Sorry about the trouble. Maestral is close to stable 1.0.0 release and there will be fewer structural changes from now on.

**Comment by someone1233** [comment]
tyvm that worked great!


> That shouldn't be a problem, the sync daemon will be shut down in exactly the same way.

ok - good to know.

>Sorry about the trouble. Maestral is close to stable 1.0.0 release and there will be fewer structural changes from now on.

not at all, it works great the vast majority of the time & i appreciate all the time you must put into developing it & providing such prompt support. :hugging: take care.
