### ISSUE TITLE
crash after original Dropbox was used

### ISSUE THREAD

**Issue by idnovic** [SamSchott/maestral-dropbox#13]
right after original dropbox was closed and maestral-gui was opened in the terminal

```
 > Loading access token...
 [OK]
 > MaestralClient is ready.
Indexing...
Traceback (most recent call last):
  File "/home/idnovic/.local/bin/maestral", line 11, in <module>
    load_entry_point('maestral==0.1.2.dev0', 'console_scripts', 'maestral')()
  File "/home/idnovic/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/idnovic/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/idnovic/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/idnovic/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/idnovic/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/idnovic/.local/lib/python3.7/site-packages/maestral/console_script.py", line 31, in gui
    run()
  File "/home/idnovic/.local/lib/python3.7/site-packages/maestral/gui/main.py", line 208, in run
    maestral = Maestral()
  File "/home/idnovic/.local/lib/python3.7/site-packages/maestral/main.py", line 143, in __init__
    self.start_sync()
  File "/home/idnovic/.local/lib/python3.7/site-packages/maestral/main.py", line 194, in start_sync
    self.monitor.start()
  File "/home/idnovic/.local/lib/python3.7/site-packages/maestral/monitor.py", line 555, in start
    self.upload_local_changes_after_inactive()
  File "/home/idnovic/.local/lib/python3.7/site-packages/maestral/monitor.py", line 601, in upload_local_changes_after_inactive
    events = self._get_local_changes()
  File "/home/idnovic/.local/lib/python3.7/site-packages/maestral/monitor.py", line 634, in _get_local_changes
    if self.client.get_local_rev(dbx_path) is not None:
  File "/home/idnovic/.local/lib/python3.7/site-packages/maestral/client.py", line 390, in get_local_rev
    rev = rev_dict[dbx_path]
TypeError: 'int' object is not subscriptable

```

**Comment by idnovic** [comment]
I probably need to resync with a clean state but i think this should be handled. At least as long maestral is not stable some users may need to use dropbox original from time to time.

**Comment by idnovic** [comment]
I wanted to add that i was using the flatpak version of dropbox. Does maestral need to access any files from the dropbox install or is the dropbox folder of the files to sync enough?

**Comment by SamSchott** [comment]
Are you trying to sync the same folder with the Maestral and the official client? This currently won't work because of the way that Maestral tracks file revision numbers (Dropbox does this extended attributes, but that requires a file system which supports them). 

Even if I would fix this particular bug, which comes from the file '.dropbox' being overwritten by the official client, there will be whole number of apparent sync conflicts without other changes.

**Comment by idnovic** [comment]
okay I see makes sense. How can I force a full resync then?

**Comment by SamSchott** [comment]
You can delete the Dropbox folder itself, or unlink and relink in the preference pane. You will then need to go through the setup dialog again...

There are some changes which I can make to prevent crashes when sync dropbox folder with both Maestral and the official client. But it will be difficult to cover all cases of possible sync conflicts.

**Comment by idnovic** [comment]
okay that did work. I thing because I had "show hidden files" disabled that I may did not delete all files.
