### ISSUE TITLE
Current build crashes with GUI

### ISSUE THREAD

**Issue by bbaserdem** [SamSchott/maestral-dropbox#32]
I am running arch linux. Currently, maestral from the stable release works fine. However, if I build from the master branch, on launching maestral-gui I have the following error;

```
% maestral gui
Gkr-Message: 08:39:03.802: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files
 > Loading access token...
 > MaestralClient is ready.
Up to date
Indexing...
Up to date
Up to date
Up to date
QImage::pixel: coordinate (0,0) out of range
qt.qpa.xcb: QXcbConnection: XCB error: 2 (BadValue), sequence: 743, resource id: 0, major code: 1 (CreateWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 744, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 745, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 746, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 748, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 749, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 750, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 755, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 756, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 757, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 760, resource id: 121634822, major code: 2 (ChangeWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 761, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 764, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 765, resource id: 121634822, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 766, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 769, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 770, resource id: 121634822, major code: 129 (Unknown), minor code: 2
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 771, resource id: 121634822, major code: 19 (DeleteProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 773, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 775, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 776, resource id: 121634822, major code: 19 (DeleteProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 778, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 779, resource id: 121634822, major code: 12 (ConfigureWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 795, resource id: 121634822, major code: 2 (ChangeWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 796, resource id: 121634822, major code: 2 (ChangeWindowAttributes), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 797, resource id: 121634822, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 798, resource id: 121634822, major code: 19 (DeleteProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 799, resource id: 121634822, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 800, resource id: 121634822, major code: 19 (DeleteProperty), minor code: 0
^CSyncing...
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/maestral/gui/main.py", line 309, in on_info_signal
    def on_info_signal(self, status):
KeyboardInterrupt
/usr/bin/maestral-gui: line 6:  2983 Aborted                 (core dumped) maestral gui
```

I used ctrl-c to quit. The gui does not appear. I have all the libraries up to date.

**Comment by SamSchott** [comment]
That looks a problem related to Qt, which are notoriously difficult to debug. Everything runs fine on Ubuntu...

I know its a bit tedious, but could you test which commit started this error? I suspect it may be one of the following: ecf88abca2cef101d451bb6b827743663651bd5a, 34f305cf82dd187b87ed38fe1979804aa6f2c537, e4ba13ed3251376a20165b8620df017f08fb9ae0, 953956bc420156843c77ac00540726a77685b0b3, 2628453f7bd24995092b0813bfec4137a51101bd, de8d1f1687b2e56e662d5607e8aba726c74db249.

**Comment by bbaserdem** [comment]
I'll give info on the builds;

* [953956b](https://github.com/SamSchott/maestral-dropbox/commit/953956bc420156843c77ac00540726a77685b0b3) gui works!
* [2628453](https://github.com/SamSchott/maestral-dropbox/commit/2628453f7bd24995092b0813bfec4137a51101bd) getting the qt error as in my first post.
* [de8d1f1](https://github.com/SamSchott/maestral-dropbox/commit/de8d1f1687b2e56e662d5607e8aba726c74db249) I'm getting a different error, will post it below.
* [44c7387](https://github.com/SamSchott/maestral-dropbox/commit/44c7387905c1bd02aa5e53777d7dd181de3b4149) Getting the same error as in my first post.

The error I get with de8d1f1 is;

```
Gkr-Message: 13:53:25.348: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files
QImage::pixel: coordinate (0,0) out of range
Traceback (most recent call last):
  File "/usr/bin/maestral", line 11, in <module>
    load_entry_point('maestral==0.2.4.dev1', 'console_scripts', 'maestral')()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/maestral/console_script.py", line 31, in gui
    run()
  File "/usr/lib/python3.7/site-packages/maestral/gui/main.py", line 424, in run
    maestral_gui = MaestralGuiApp()
  File "/usr/lib/python3.7/site-packages/maestral/gui/main.py", line 96, in __init__
    self.setIcon(self.icons[DISCONNECTED])
  File "/usr/lib/python3.7/site-packages/maestral/gui/main.py", line 389, in setIcon
    if platform.system() == "Linux" and self.menu.devicePixelRatio() > 1:
AttributeError: 'MaestralGuiApp' object has no attribute 'menu'
```

**Comment by SamSchott** [comment]
Great that you like the client! Yes, I am in a very similar situation here, I need Dropbox for work but do not want to install the full Dropbox client with embedded Chromium on my Mac.

Ok, so your problem seems to be with the code that should detect high-DPI scaling. Which desktop environment are you running, and are you using high-DPI scaling? And which version of Qt / PyQt are you using?

Finally, what output to you get from `gsettings get org.gnome.desktop.interface scaling-factor` in the terminal?

I will disable the automatic high-DPI detection for now, and rely on Qt to do its job (and the user possibly forcing it by setting environment variables) since I ran into problems with the code on a few other platforms as well. But it will be nice to know what exactly failed in your case.

**Comment by SamSchott** [comment]
Right, the latest commit should have fixed your issue. Could you give it a try?

**Comment by bbaserdem** [comment]
The problem is fixed with the latest commit. I also wrote a build script for Arch User Repository [here](https://aur.archlinux.org/packages/maestral-git/).

My desktop environment is bspwm; so not a common use case. The command does not work, since I don't use gnome. I do not have DPI scaling.

Pyqt5 is version 5.13.0 along with all of the qt ones.

**Comment by SamSchott** [comment]
That is good news. But I am still very confused about the bug. If python cannot find a `gsettings` command in the current PATH, Maestral should not set any environment variables for Qt high-DPI scaling. But for some reason, removing those lines fixes the UI for you...

I appreciate the build script!

**Comment by bbaserdem** [comment]
I apologize, I must have mistyped the command in haste. I do apparently have gsettings. The result is `uint32 0`.

**Comment by SamSchott** [comment]
That does explain the problems. A scaling factor of 0 will be difficult to handle!
