### ISSUE TITLE
[BUG] Doesn't like certain files but doesn't tell which ones

### ISSUE THREAD

**Issue by peterhoeg** [SamSchott/maestral-dropbox#39]
**Describe the bug**
There are some files in dropbox, that maestral (or maybe dropbox) doesn't like, but doesn't tell me which so I can't really do anything about it:
```
dropbox.exceptions.ApiError: ApiError('30f1d5eeaac843c1ff555c04e08561b8', UploadError('path', UploadWriteFailed(reason=WriteError('disallowed_name', None), upload_session_id='AAAAAAAAM9FqZ1pyxzgvlA')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/jjccwr48ahjxvzg7v6gigacwhsj8k2m4-maestral-gui-0.2.6/lib/python3.7/site-packages/maestral/monitor.py", line 188, in wrapper
    res = func(self, *args, **kwargs)
  File "/nix/store/jjccwr48ahjxvzg7v6gigacwhsj8k2m4-maestral-gui-0.2.6/lib/python3.7/site-packages/maestral/monitor.py", line 710, in _apply_event
    self._on_created(evnt)
  File "/nix/store/jjccwr48ahjxvzg7v6gigacwhsj8k2m4-maestral-gui-0.2.6/lib/python3.7/site-packages/maestral/monitor.py", line 812, in _on_created
    md = self.client.upload(path, dbx_path, autorename=True, mode=mode)
  File "/nix/store/jjccwr48ahjxvzg7v6gigacwhsj8k2m4-maestral-gui-0.2.6/lib/python3.7/site-packages/maestral/client.py", line 282, in upload
    raise to_maestral_error(exc, dbx_path) from exc
maestral.errors.PathError: Could not upload file: Dropbox will not save the file or folder because of its name.
2019-08-13 21:50:09 maestral.monitor ERROR: Sync error
Traceback (most recent call last):
  File "/nix/store/jjccwr48ahjxvzg7v6gigacwhsj8k2m4-maestral-gui-0.2.6/lib/python3.7/site-packages/maestral/client.py", line 257, in upload
    f.read(), dbx_path, client_modified=mtime_dt, **kwargs)
  File "/nix/store/5ajzqlpk5l37lc4x2q4sb5hkszvf9kir-python3.7-dropbox-9.4.0/lib/python3.7/site-packages/dropbox/base.py", line 2458, in files_upload
    f,
  File "/nix/store/5ajzqlpk5l37lc4x2q4sb5hkszvf9kir-python3.7-dropbox-9.4.0/lib/python3.7/site-packages/dropbox/dropbox.py", line 296, in request
    user_message_locale)
dropbox.exceptions.ApiError: ApiError('0c98289b3e80e3259fe670566c2d7f98', UploadError('path', UploadWriteFailed(reason=WriteError('disallowed_name', None), upload_session_id='AAAAAAAAM9IdJt1oBQwYjg')))
```

**To Reproduce**

Happens consistently but I obviously don't know which files are the case.

**Expected behaviour**
maestral to tell me which files were rejected.

**System (please complete the following information):**
 - OS: NixOS unstable
 - Desktop environment: KDE 5.15.5
 - Qt version: 5.12.0

**Comment by SamSchott** [comment]
Are you running Maestral with GUI, or as a command line script? The GUI has a "Sync Issues" panel which you can access from the main menu where files with sync errors are listed.

The command line client indeed lacks support for this at the moment...

**Comment by peterhoeg** [comment]
>   The command line client indeed lacks support for this at the moment...

The CLI client indeed.

**Comment by SamSchott** [comment]
In this case, you can find out which file caused the error by running Maestral interactively in a Python interpreter:
```python
form maestral.main import Maestral
m = Maestral()  # starts syncing
err = m.sync.sync_errors.get()  # gets the last error from the sync_errors queue
print(err.local_path)  # print the local path of the file
```
It's not very elegant, but it works.

**Comment by SamSchott** [comment]
Right, the newest version of maestral now supports listing all sync errors in the command line. Just run `maestral daemon errors` to print the list. This assumes that you have a running instance of meastral, created with `maestral daemon start` or with `maestral sync` in another terminal.
