### ISSUE TITLE
[BUG] Application cannot start

### ISSUE THREAD

**Issue by upal212** [SamSchott/maestral-dropbox#41]
**Describe the bug**
2019-08-14 15:36:46 maestral.main ERROR: Authentication error: Maestral's access to your Dropbox has been revoked. Please relink to continue syncing.
Traceback (most recent call last):
  File "maestral/client.py", line 118, in get_account_info
  File "dropbox/base.py", line 4508, in users_get_current_account
  File "dropbox/dropbox.py", line 274, in request
  File "dropbox/dropbox.py", line 365, in request_json_string_with_retry
  File "dropbox/dropbox.py", line 463, in request_json_string
dropbox.exceptions.AuthError: AuthError('0fc15289f761ee76a47f75086dbf2a59', AuthError('invalid_access_token', None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maestral/main.py", line 120, in wrapper
  File "maestral/main.py", line 205, in get_account_info
  File "maestral/client.py", line 120, in get_account_info
maestral.errors.DropboxAuthError: Authentication error: Maestral's access to your Dropbox has been revoked. Please relink to continue syncing.
2019-08-14 15:40:51 maestral.main ERROR: Authentication error: Maestral's access to your Dropbox has been revoked. Please relink to continue syncing.
Traceback (most recent call last):
  File "maestral/client.py", line 118, in get_account_info
  File "dropbox/base.py", line 4508, in users_get_current_account
  File "dropbox/dropbox.py", line 274, in request
  File "dropbox/dropbox.py", line 365, in request_json_string_with_retry
  File "dropbox/dropbox.py", line 463, in request_json_string
dropbox.exceptions.AuthError: AuthError('ae966154fc18f3f0da1a1b9588ca5e9a', AuthError('invalid_access_token', None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maestral/main.py", line 120, in wrapper
  File "maestral/main.py", line 205, in get_account_info
  File "maestral/client.py", line 120, in get_account_info
maestral.errors.DropboxAuthError: Authentication error: Maestral's access to your Dropbox has been revoked. Please relink to continue syncing.

**To Reproduce**
Nothing yet.

**Expected behaviour**
After revoking the app auth, it should ask to re-add it again.

**System (please complete the following information):**
macOS Mojave

**Comment by SamSchott** [comment]
Yes, thats a known issue. It has been already fixed in the development branch - the fix will be included in the next release (v0.2.7).

**Comment by upal212** [comment]
Thank you for the update, and your great work on the project!

**Comment by SamSchott** [comment]
Great you like it :) The issue should be fixed in the newest release. Could you check if it works for you?

**Comment by upal212** [comment]
Yup, and it is working 😄 
![Screenshot 2019-08-15 at 2 08 37 PM](https://user-images.githubusercontent.com/25398100/63083656-efaa5e00-bf66-11e9-8187-7462593aae36.png)

Thank you for the great update!

**Comment by SamSchott** [comment]
Good!
