### ISSUE TITLE
[BUG] Maestral crashes when trying to migrate config files

### ISSUE THREAD

**Issue by Gabrock94** [SamSchott/maestral-dropbox#60]
**Describe the bug**
`giulio@giulio-HP-ProBook-430-G3:~/Desktop/maestral-dropbox-master$ maestral start
Traceback (most recent call last):
  File "/usr/local/bin/maestral", line 11, in <module>
    load_entry_point('maestral==0.4.1', 'console_scripts', 'maestral')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/maestral-0.4.1-py3.6.egg/maestral/cli.py", line 205, in start
    check_for_updates()
  File "/usr/local/lib/python3.6/dist-packages/maestral-0.4.1-py3.6.egg/maestral/cli.py", line 75, in check_for_updates
    from maestral.config.main import CONF
  File "/usr/local/lib/python3.6/dist-packages/maestral-0.4.1-py3.6.egg/maestral/config/main.py", line 81, in <module>
    migrate_config_files()
  File "/usr/local/lib/python3.6/dist-packages/maestral-0.4.1-py3.6.egg/maestral/config/base.py", line 134, in migrate_config_files
    shutil.copytree(old_path, new_path)
  File "/usr/lib/python3.6/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/giulio/.config/maestral'
giulio@giulio-HP-ProBook-430-G3:~/Desktop/maestral-dropbox-master$ 
`

**To Reproduce**
Install Maestral, set it up, uninstall it, reinstall and try to log in.

**Expected behaviour**
Maestral is supposed to allow me to run a configuration.

**System (please complete the following information):**
 - Maestral version:
 - OS: Linux Mint 19.2
 - Desktop environment: Cinnamon 4.2.4
 - Qt version: 5

**Comment by SamSchott** [comment]
I believe that this is an issue when updating from version 0.2.4. In versions 0.2.5 and higher, the location where config files are saved has changed from "~/.maestral" to "~/.config/maestral" and subsequent versions will try to migrate the old files if those are detected. Did you have v0.2.4 installed at any point? For some reason, deleting the old files after the migration seems not to have worked in your case.

Could you confirm that the folder "~/.config/maestral" has been created properly and then delete the old folder "~/.maestral" manually? This should take care of the issues. 

Your linked Dropbox account and sync status should of course persist between installs.

**Comment by Gabrock94** [comment]
@SamSchott thanks for your help. Removing both the folder and rebulding the config files worked for me! Thanks again
