### ISSUE TITLE
Inotify watch limit reached for large Dropbox

### ISSUE THREAD

**Issue by imerelli** [SamSchott/maestral-dropbox#75]
Hi, I have a problem with maestral, since it hangs up while syncing files. 
Then when I stop it and then I try to restart the server I get this error. 

$ maestral stop --config-name="hsr"                                                                                                                                                                                  
Stopping Maestral...        [OK]
$ maestral start --config-name="hsr"                                                                                                                                                                                 
Starting Maestral...2019-12-11 21:50:12 maestral.sync.daemon ERROR: Could communicate with Maestral daemon
Starting Maestral...        [FAILED]

If I erase the configuration file, then it starts again, but in some hours it will hang up again.

**Comment by SamSchott** [comment]
Oh, I am sorry to hear this. Could you maybe give some more information to help with troubleshooting?

1. What operating system and which version of maestral do you use?
2. When you say it "hangs up", what is the output of `maestral status -c hsr`? If you get any output, it means that the daemon is still responsive, just not syncing anymore.
3. What is the output of `maestral log show -c hsr` when it hangs? Any error messages there?
4. Can you set the logger to debug, with `maestral log level DEBUG -c hsr `?
5. What is the log output when maestral fails to start?
6. Does starting it with `maestral start -f -c hsr` work? This will start maestral in the foreground instead of creating a daemon.

**Comment by imerelli** [comment]
Hi, below probably the explanation of the problem. 
My Dropbox is quite huge. Running latest version on centos.

$ maestral start -f 
2019-12-12 14:07:22 maestral.sync.monitor ERROR: Maestral index has become corrupted. Please rebuild.
Traceback (most recent call last):
  File "/home/imerelli/.local/lib/python3.6/site-packages/maestral/sync/monitor.py", line 491, in _load_rev_dict_from_file
    rev_dict_cache = umsgpack.unpack(f)
  File "/home/imerelli/.local/lib/python3.6/site-packages/umsgpack.py", line 953, in _unpack3
    return _unpack(fp, options)
  File "/home/imerelli/.local/lib/python3.6/site-packages/umsgpack.py", line 863, in _unpack
    return _unpack_dispatch_table[code](code, fp, options)
  File "/home/imerelli/.local/lib/python3.6/site-packages/umsgpack.py", line 838, in _unpack_map
    k = _unpack(fp, options)
  File "/home/imerelli/.local/lib/python3.6/site-packages/umsgpack.py", line 862, in _unpack
    code = _read_except(fp, 1)
  File "/home/imerelli/.local/lib/python3.6/site-packages/umsgpack.py", line 639, in _read_except
    raise InsufficientDataException()
maestral.sync.errors.RevFileError: 'None': Corrupted index. Maestral index has become corrupted. Please rebuild.
Traceback (most recent call last):
  File "/home/imerelli/.local/lib/python3.6/site-packages/maestral/sync/daemon.py", line 109, in start_maestral_daemon
    m = ExposedMaestral(run=run)
  File "/home/imerelli/.local/lib/python3.6/site-packages/maestral/sync/main.py", line 204, in __init__
    self.start_sync()
  File "/home/imerelli/.local/lib/python3.6/site-packages/maestral/sync/main.py", line 501, in start_sync
    self.monitor.start()
  File "/home/imerelli/.local/lib/python3.6/site-packages/maestral/sync/monitor.py", line 1887, in start
    self.local_observer_thread.start()
  File "/home/imerelli/.local/lib/python3.6/site-packages/watchdog/observers/api.py", line 255, in start
    emitter.start()
  File "/home/imerelli/.local/lib/python3.6/site-packages/watchdog/utils/__init__.py", line 110, in start
    self.on_thread_start()
  File "/home/imerelli/.local/lib/python3.6/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/imerelli/.local/lib/python3.6/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/imerelli/.local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 199, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/imerelli/.local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 387, in _add_dir_watch
    self._add_watch(full_path, mask)
  File "/home/imerelli/.local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 401, in _add_watch
    Inotify._raise_error()
  File "/home/imerelli/.local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 413, in _raise_error
    raise OSError("inotify watch limit reached")
OSError: inotify watch limit reached

**Comment by SamSchott** [comment]
That's indeed the problem. Inotify by default only watches up to 8192 items but you can increase this limit. Instructions are given for instance here: https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by SamSchott** [comment]
This also explains why syncing initially worked for you but eventually crashed.

I'll catch this error in a future version and notify the user.

**Comment by SamSchott** [comment]
v0.5.0 added user notification with instructions to increase inotify limit.
